name: Bandit Security Check

on:
  push:
    branches:
      - main
      - dev
      - "feature/*"
  pull_request:
    branches:
      - main
      - dev
      - "feature/*"

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Bandit
        run: bandit -r .